### PR TITLE
Fix incorrect TypeScript definitions for Telegraf.launch()

### LINKED ISSUE #762: [ts] Telegraf.launch(): options.webhook type definition is incorrect
## Context

* Telegraf.js Version: 3.32.0
* Node.js Version: 10.16.3
* Operating System: Ubuntu 18.04.3 LTS

## Expected Behavior

Be able to pass webhook options to Telegraf.launch()

## Current Behavior

[This example](https://github.com/telegraf/telegraf/blob/develop/docs/examples/webhook-bot.js):

```typescript
bot.launch({
  webhook: {
    domain: 'https://---.localtunnel.me',
    port: 3000
  }
})
```

results in a TypeScript error:
```
Argument of type '{ webhook: { domain: string; port: number; }; }' is not assignable to parameter of type '{ polling?: { timeout?: number | undefined; limit?: number | undefined; allowedUpdates?: UpdateType[] | undefined; } | undefined; webhook?: { webhookPath: string; tlsOptions: TlsOptions | null; port: number; host?: string | undefined; } | undefined; }'.
  Types of property 'webhook' are incompatible.
    Type '{ domain: string; port: number; }' is not assignable to type '{ webhookPath: string; tlsOptions: TlsOptions | null; port: number; host?: string | undefined; }'.
      Object literal may only specify known properties, and 'domain' does not exist in type '{ webhookPath: string; tlsOptions: TlsOptions | null; port: number; host?: string | undefined; }'.
      Property 'tlsOptions' is missing
```

The current definition of `webhook`:

```typescript
webhook?: { webhookPath: string, tlsOptions: TlsOptions | null, port: number, host?: string }
```

Judging by the source code, launch() accepts these webhook options:
```typescript
domain?: string; // This one is missing
hookPath?: string; // This one is incorrectly called webhookPath; webhookPath is NOT used in the code
port: number;
host?: string;
tlsOptions?: TlsOptions | null; // Looks like it can be undefined, as the example code does not pass it
cb?: (req: IncomingMessage, res: ServerResponse) => void; // This one is missing
```

### PR DESCRIPTION
**Pull request by sjinks**
# Description

TypeScript definitions for `Telegraf.launch()` were incorrect: launch() accepts more options than advertised.

Fixes #762

## Type of change

Please delete options that are not relevant.

- [x] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Added tests to `typings/tests.ts`

**Test Configuration**:
* Node.js Version: v12.10.0
* Operating System: Ubuntu 16.04

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: typings/index.d.ts [hunk 1]
```diff
@@ -1008,6 +1008,60 @@ export interface ComposerConstructor {
...
+
+  /**
+   * List the types of updates you want your bot to receive
+   */
+  allowedUpdates?: tt.UpdateType[] | tt.UpdateType | null
+
+  /**
+   * Polling stop callback
+   */
+  stopCallback?: () => void | null
```
Comment (sjinks) [inline typings/index.d.ts]: `null` because the documentation explicitly mentions that the default value is null

File: typings/index.d.ts [hunk 2]
```diff
@@ -1008,6 +1008,60 @@ export interface ComposerConstructor {
...
+
+  /**
+   * Limits the number of updates to be retrieved
+   */
+  limit?: number
+
+  /**
+   * List the types of updates you want your bot to receive
+   */
+  allowedUpdates?: tt.UpdateType[] | tt.UpdateType | null
```
Comment (sjinks) [inline typings/index.d.ts]: * `null` because the documentation explicitly mentions the default value is null.
  * `tt.UpdateType` because of this code in `startPolling`: 
```js
Array.isArray(allowedUpdates) ? allowedUpdates : [`${allowedUpdates}`]
```

File: typings/index.d.ts [hunk 3]
```diff
@@ -1051,17 +1105,19 @@ export interface Telegraf<TContext extends ContextMessageUpdate> extends Compose
    * @param timeout Poll timeout in seconds
    * @param limit Limits the number of updates to be retrieved
    * @param allowedUpdates List the types of updates you want your bot to receive
+   * @param stopCallback Polling stop callback
```
Comment (sjinks) [inline typings/index.d.ts]: Added because the original JS code accepts `stopCallback` parameter

File: typings/index.d.ts [hunk 4]
```diff
@@ -1051,17 +1105,19 @@ export interface Telegraf<TContext extends ContextMessageUpdate> extends Compose
...
-  startPolling(timeout?: number, limit?: number, allowedUpdates?: tt.UpdateType[]): Telegraf<TContext>
+  startPolling(timeout?: number, limit?: number, allowedUpdates?: tt.UpdateType[] | tt.UpdateType | null, stopCallback?: () => void | null): Telegraf<TContext>
 
   /**
    * Start listening @ https://host:port/hookPath for Telegram calls.
    * @param hookPath Webhook url path (see Telegraf.setWebhook)
    * @param tlsOptions TLS server options. Pass null to use http
    * @param port Port number
    * @param host Hostname
+   * @param cb A callback function suitable for the http[s].createServer() method to handle a request.
```
Comment (sjinks) [inline typings/index.d.ts]: Added because the original JS code accepts `cb` parameter
